# Generated by Django 3.0.5 on 2020-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
        ),
    ]
