# Generated by Django 3.0.5 on 2020-08-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminderApi', '0003_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminderApi.ReminderCategory'),
        ),
    ]
