# Generated by Django 3.0.5 on 2020-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderApi', '0004_reminder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='tags',
            field=models.ManyToManyField(null=True, to='reminderApi.ReminderTag'),
        ),
    ]
